<a href="https://colab.research.google.com/github/Miguelbuga/proyecto_combinatoria/blob/main/JsonVardi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd

In [22]:
data = pd.read_excel('/content/VardiCuentas.xlsx', sheet_name = 'Smart-Eco')

In [23]:
data

,number,id,service_name,AB,AC,AL,AM,AS,CT,EN,GA,IN,TE,TF,TM,TV
0,11674230,cs6t8m9n41c81tgj852065n,TELEFONIA MOVIL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,10556533,cs6t8lln3yg0htgy0r31pcg,TELEFONIA MOVIL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,18738728,cs6t8lmn3ym96tgipq2gpha,TELEFONIA MOVIL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,20001584,clsccv1n51079915fb2qmqrji5o8,INTERNET,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,20130960,clulooxm9881091f92qaegz7tcx,INTERNET,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575,264564,crgb1hkco4p2htg3iemfqe6,AGUA,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
576,9000474022,cs87a199teihmtg2qf19pj0,TELEFONIA MOVIL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
577,10581153,cri7bazo8uwsdtguk2svzxr,AGUA,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
578,677770,crgb1hlco6v2ftghdksuap8,ENERG√çA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
579,1102221,cri7bb1o8ycsdtge24qtn6e,AGUA,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
dfError = data[data['AB'] == None]
dfError

Empty DataFrame
Columns: [number, id, service_name, AB, AC, AL, AM, AS, CT, EN, GA, IN, TE, TF, TM, TV]
Index: []

In [25]:
dfdata = data.dropna()
dfdata

,number,id,service_name,AB,AC,AL,AM,AS,CT,EN,GA,IN,TE,TF,TM,TV
0,11674230,cs6t8m9n41c81tgj852065n,TELEFONIA MOVIL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,10556533,cs6t8lln3yg0htgy0r31pcg,TELEFONIA MOVIL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,18738728,cs6t8lmn3ym96tgipq2gpha,TELEFONIA MOVIL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,20001584,clsccv1n51079915fb2qmqrji5o8,INTERNET,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,20130960,clulooxm9881091f92qaegz7tcx,INTERNET,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,514143,cri7bb1o8ymsdtgo4gdjpi5,AGUA,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
575,264564,crgb1hkco4p2htg3iemfqe6,AGUA,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
576,9000474022,cs87a199teihmtg2qf19pj0,TELEFONIA MOVIL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
577,10581153,cri7bazo8uwsdtguk2svzxr,AGUA,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
579,1102221,cri7bb1o8ycsdtge24qtn6e,AGUA,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [76]:
id = []
json_data = []
lastservices = []
for indice, fila in data.iterrows():
  opcional = False
  id.append(fila['id'])
  service = {
      'id': fila['id'],
      'number': fila['number'],
      'service_name': fila['service_name'],
      'services' : {}
  }

  if fila['AB'] == 1:
    service['services']['AB'] = {"AB":True}
    opcional = True

  if fila['AC'] == 1:
    service['services']['AC'] = {"AC":True}
    opcional = True

  if fila['AM'] == 1:
    service['services']['AM'] = {"AM":True}
    opcional = True

  if fila['AS'] == 1:
    service['services']['AS'] =  {"AS": True}
    opcional = True

  if fila['CT'] == 1:
    service['services']['CT'] =  {"CT": True}
    opcional = True

  if fila['EN'] == 1:
    service['services']['EN'] =  {"EN": True}
    opcional = True

  if fila['GA'] == 1:
    service['services']['GA'] =  {"GA": True}
    opcional = True

  if fila['IN'] == 1:
    service['services']['IN'] =  {"IN": True}
    opcional = True

  if fila['TE'] == 1:
    service['services']['TE'] =  {"TE": True}
    opcional = True

  if fila['TF'] == 1:
    service['services']['TF'] =  {"TF": True}
    opcional = True

  if fila['TM'] == 1:
    service['services']['TM'] =  {"TM": True}
    opcional = True

  if fila['TV'] == 1:
    service['services']['TV'] =  {"TV": True}
    opcional = True

  if fila['IN'] == 1 and fila['TE'] == 1 :
    if fila['service_name']  == 'INTERNET':
        service['services']['IN'] = {"IN": True, "cdServic": True}
        service['services']['TE'] = {"TE": True}
    if fila['service_name']  == 'TELEFONIA MOVIL':
        service['services']['TE'] = {"TE": True, "cdServic": True}
        service['services']['IN'] = {"IN" :True}
    opcional = True

  if fila['TE'] == 1 and fila['TV'] == 1 :
    if fila['service_name']  == 'TELEVISION':
        service['services']['TV'] = {"TV": True, "cdServic": True}
        service['services']['TE'] = {"TE": True}
    if fila['service_name']  == 'TELEFONIA MOVIL':
        service['services']['TE'] = {"TE": True, "cdServic": True}
        service['services']['TV'] = {"TV" :True}
    opcional = True

  if opcional:
    json_data.append(service)

  lastservices.append(service['services'])

structure = {
        'id' : id,
        #'info_account':json_data,
        'services':lastservices
}

In [62]:
datafilter = data[data['id'] == 'cs9vtcq948lwjtg97s0ic56']
datafilter

,number,id,service_name,AB,AC,AL,AM,AS,CT,EN,GA,IN,TE,TF,TM,TV
323,8224072001,cs9vtcq948lwjtg97s0ic56,TELEFONIA MOVIL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [64]:
x = structure.get('id') == 'cs9vtcq948lwjtg97s0ic56'
x

False

In [60]:
dffindid = pd.DataFrame(structure.get('id'))
dffindservices = pd.DataFrame(structure.get('services'))

dffindid.to_excel('id.xlsx')
dffindservices.to_excel('services.xlsx')

In [61]:
dffinderror = pd.DataFrame(structure.get('info_account'))
dffinderror
dffinderror.to_excel('info_account.xlsx')

In [78]:
df = pd.DataFrame(structure)
df.to_excel("structure_service.xlsx")
df

ValueError: All arrays must be of the same length

In [69]:
for i in range(len(structure.get('info_account'))):
  if structure.get('info_account')[i]['number']==8224072001:
    print(structure.get('info_account')[i]['service_name'])
    print(structure.get('info_account')[i]['services'])

In [70]:
unique_list = []

for i in range(len(structure.get('info_account'))):
  unique_list.append(structure.get('info_account')[i]['number'])

inp_list = unique_list
unique_list = list(dict.fromkeys(inp_list))
print(len(unique_list))

528

In [ ]:
dataAccount  = data[['id','number','account_vardi']]

#for indice, row in dataAccount.iterrows():
  #x = row['number']
  #y = str(row['account_vardi'])
  #dataAccount['validaci√≥n'] = x == y


#for i in range(len(dataAccount['id'])):
  #dataAccount['verification'] = [dataAccount['number'][i]==str(dataAccount['account_vardi'][i])]


print(len(dataAccount['account_vardi']))
print(len(dataAccount['number']))


dataAccount = dataAccount.assign(comparative = dataAccount['number'] == dataAccount['account_vardi'].astype(str))


dataAccount.to_excel("data.xlsx")



print(dataAccount)
# Supongamos que tienes un DataFrame df
df = pd.DataFrame({
    'columna_a': [1, 2, 3, 4, 5],
    'columna_b': [5, 4, 3, 2, 1]
})

# Comparar dos columnas y agregar los resultados como una nueva columna
df = df.assign(comparacion=df['columna_a'] == df['columna_b'].astype(str))

print(df)

#print(len(dataAccount['id']))

#dataAccount['number'][1]

#str(dataAccount['account_vardi'][1])



#if(str(dataAccount.iloc[2]['account_vardi']) == str(dataAccount.iloc[2]['number'])):
  #print('Si')
#else:
  #print('False')

556
556
                          id         number account_vardi  comparative
0    cri7bayo8tysdtg670lf6ig  0700010078306  700010078306        False
1    cs87a2u9thshmtgcoptouce    24032241891   24032241891         True
2    cri7bayo8twsdtgizohwvn6  0700010079441  700010079441        False
3    cs6t8lnn3yo0htgy2o2nxbf     8220188771    8220188771         True
4     cs87a449tk0hmtgndi1ds9     8215346413    8215346413         True
..                       ...            ...           ...          ...
551    cs9vtd1948xwjtg41weu4    60574617821   60574617821         True
552  cs9vtck948dqutg292ze3tq       76767920      76767920         True
553  cs9vtco948jqutgunm0up7l     8224065459    8224065459         True
554  cs9vtcq948lwjtg97s0ic56     8224072001    8224072001         True
555  cs9vtd3948zwjtg1v5ljkb6        EN95740       EN95740         True

[556 rows x 4 columns]
   columna_a  columna_b  comparacion
0          1          5        False
1          2          4        False
2          3          3        False
3          4          2        False
4          5          1        False